                                                   Data Types and Structures Questions

1.  What are data structures, and why are they important?

     Data Structures is way of organizing and storing data so that it can be acccessed and manipulated effeciently.
     Ex: string, list, set, tuples, dictionary, array.
     They are very Efficient, scalable and Flexibility.

2. Explain the difference between mutable and immutable data types with examples?

    Mutable data types can be changed after creation (Ex:lists), while immutable data types cannot be changed once created (Ex:strings).

3. What are the main differences between lists and tuples in Python?

    Lists are mutable and can be modified after creation, while tuples are immutable and cannot be changed once defined. Lists use square brackets[], whereas tuples use parentheses().

4. Describe how dictionaries store data?

    Dictionaries in Python store data as key-value pairs. Each key is unique and maps to a specific value.

5. Why might you use a set instead of a list in Python?

    we might use a set instead of a list in Python when you need to store unique elements and perform fast membership tests.Sets automatically remove duplicates and offer faster lookup compared to lists.

6.  What is a string in Python, and how is it different from a list?

    A string in Python is a sequence of characters enclosed in quotes (Ex:"hello"), and it is immutable, meaning it cannot be changed after creation. A list is a collection of items (Ex: [1, 2, 3]) that is mutable, so its elements can be modified.

7. How do tuples ensure data integrity in Python?

    Tuples ensure data integrity in Python by being immutable,meaning their contents cannot be changed after creation. This prevents accidental modification and makes them reliable for storing fixed collections of data.

8. What is a hash table, and how does it relate to dictionaries in Python?

    A hash table is a data structure that stores data in an associative manner using key-value pairs.A dictionary is an implementation of a hash table. When you create a dictionary, Python uses hashing to map each key to its corresponding value, allowing for fast lookups, insertions, and deletions.So, dictionaries in Python are built on the concept of hash tables.

9. Can lists contain different data types in Python?

    Yes, lists in Python3 can contain different data types. Ex: my_list = [1, "Mounika", 3.14, True]

10.  Explain why strings are immutable in Python?

      Strings are immutable in Python because once a string is created, its contents cannot be changed. This design ensures data integrity, security, and performance—especially when strings are used as keys in dictionaries or shared across multiple parts of a program.Instead of modifying a string, Python creates a new one when changes are needed.

11. What advantages do dictionaries offer over lists for certain tasks?

    Dictionaries offer faster lookups using keys and allow association of values with unique identifiers,making them ideal for tasks like storing user data,configurations,or counting items.Unlike lists,you don’t need to search through indexes to find a specific value.

12. Describe a scenario where using a tuple would be preferable over a list.

    Use a tuple when storing fixed data like coordinates(x, y) or dates(day, month, year)that shouldn't change,ensuring data integrity.

13. How do sets handle duplicate values in Python?

    Sets automatically remove duplicates,storing only unique elements,which helps in filtering and membership testing.

14. How does the “in” keyword work differently for lists and dictionaries?
     
    In lists-"in" checks for values whereas in dictionaries-it checks for keys, not values.

15. Can you modify the elements of a tuple? Explain why or why not?

    No,tuples are immutable,meaning their elements cannot be changed once defined.

16.  What is a nested dictionary, and give an example of its use case?

     A nested dictionary is a dictionary inside another dictionary.Ex:students = {'John': {'age': 20, 'grade': 'A'}}

17. Describe the time complexity of accessing elements in a dictionary?

    Accessing elements in a dictionary has O(1) time complexity due to hashing.

18. In what situations are lists preferred over dictionaries?

    Lists are preferred when order matters or when storing sequential data without key-value pairs.

19. Why are dictionaries considered unordered, and how does that affect data retrieval?

    Dictionaries were unordered before Python 3.7,meaning item order wasn't guaranteed,affecting predictable iteration.

20. Explain the difference between a list and a dictionary in terms of data retrieval.

    Lists retrieve data by index, while dictionaries retrieve data by key, offering faster access for labeled data.

                                                         Practical Questions

1. Write a code to create a string with your name and print it

In [ ]:
My_name = "Mounika"
print(My_name)

Mounika

2. Write a code to find the length of the string "Hello World".

In [ ]:
Str = "Hello World"
print(len(Str))

11

3.  Write a code to slice the first 3 characters from the string "Python Programming"?

In [ ]:
str1 = "Python Programming"
print(str1[:3])

Pyt

4. Write a code to convert the string "hello" to uppercase.

In [ ]:
str2= "hello"
print(str2.upper())

HELLO

5. Write a code to replace the word "apple" with "orange" in the string "I like apple

In [ ]:
str3="I like apple"
print(str3.replace("apple","orange"))

I like orange

6. Write a code to create a list with numbers 1 to 5 and print it

In [ ]:
numbers=[1,2,3,4,5]
print(numbers)

[1, 2, 3, 4, 5]

7. Write a code to append the number 10 to the list [1, 2, 3, 4]

In [ ]:
n2=[1,2,3,4]
n2.append(10)
print(n2)

[1, 2, 3, 4, 10]

8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

In [ ]:
l1=[1,2,3,4,5]
l1.remove(3)
print(l1)

[1, 2, 4, 5]

9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].

In [ ]:
l2= ['a','b','c','d']
print(l2[1])

b

10. Write a code to reverse the list [10, 20, 30, 40, 50].

In [ ]:
l3=[10,20,30,40,50]
l3.reverse()
print(l3)

[50, 40, 30, 20, 10]

11. Write a code to create a tuple with the elements 100, 200, 300 and print it.

In [ ]:
t1=(100,200,300)
print(t1)

(100, 200, 300)

12.  Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')

In [ ]:
t2=('red','green','blue','green')
print(t2[-2])

blue

13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [ ]:
t3=(10,20,5,15)
print(min(t3))

5

 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [ ]:
t4=('dog','cat','rabbit')
print(t4.index('cat'))

1

15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [ ]:
t5 = ("apple", "banana", "orange")
"kiwi" in t5

False

16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.

In [ ]:
s1= {'a','b','c'}
print(s1)

{'c', 'a', 'b'}

17.  Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

In [ ]:
s2={1,2,3,4,5}
s2.clear()
print(s2)

set()

18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.

In [ ]:
s3 ={1,2,3,4}
s3.remove(4)
print(s3)

{1, 2, 3}

19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}

In [ ]:
s1 = {1,2,3}
s2 = {3,4,5}
s1 | s2

{1, 2, 3, 4, 5}

20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

In [ ]:
s1 = {1,2,3}
s2 = {2,3,4}
s1 & s2

{2, 3}

21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it

In [ ]:
d1={"name": "Mounika", "age": 24, "city": "Hyderabad"}
print(d1)

{'name': 'Mounika', 'age': 24, 'city': 'Hyderabad'}

22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

In [ ]:
d2= {'name': 'John', 'age': 25}
d2["country"]="USA"
print(d2)

{'name': 'John', 'age': 25, 'country': 'USA'}

23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [ ]:
d3={'name': 'Alice', 'age': 30}
print(d3['name'])

Alice

24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

In [ ]:
d4 = {'name': 'Bob', 'age': 22, 'city': 'New York'}
d4.pop('age')
print(d4)

{'name': 'Bob', 'city': 'New York'}

25.  Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

In [ ]:
d5= {'name': 'Alice', 'city': 'Paris'}
print('city' in d5)

True

26.  Write a code to create a list, a tuple, and a dictionary, and print them all

In [ ]:
l3=[10,20,30,40,50]
t2=('red','green','blue','green')
d5= {'name': 'Alice', 'city': 'Paris'}
print(l3)
print(t2)
print(d5)

[10, 20, 30, 40, 50]
('red', 'green', 'blue', 'green')
{'name': 'Alice', 'city': 'Paris'}

27.  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)

In [ ]:
import random
random_numbers = [random.randint(1, 100) for _ in range(5)]
random_numbers.sort()
print(random_numbers)

[24, 36, 47, 62, 76]

28. Write a code to create a list with strings and print the element at the third index

In [ ]:
ls= [ 'apple','bus','mobile','ball','umbrella']
print(ls[3])

ball

29.  Write a code to combine two dictionaries into one and print the result

In [ ]:
d4 = {'name': 'Bob', 'age': 22, 'city': 'New York'}
d1={"nam": "Mounika", "ag": 24, "cit": "Hyderabad"}
d4.update(d1)
print(d4)

{'name': 'Bob', 'age': 22, 'city': 'New York', 'nam': 'Mounika', 'ag': 24, 'cit': 'Hyderabad'}

30. Write a code to convert a list of strings into a set.

In [ ]:
ls= [ 'apple','bus','mobile','ball','umbrella']
print(set(ls))

{'bus', 'apple', 'mobile', 'umbrella', 'ball'}